
INSERT INTO books ('id','title','author','others','likes','downloads') VALUES
 (1952,'The Yellow Wallpaper','Gilman, Charlotte Perkins','',0,18324)
 (1661,'The Adventures of Sherlock Holmes','Doyle, Arthur Conan','',0,11602)
 (98,'A Tale of Two Cities','Dickens, Charles','',0,9996)
 (74,'The Adventures of Tom Sawyer','Twain, Mark','',0,8653)
 (2591,'Grimms&apos; Fairy Tales','Grimm, Jacob','Grimm, Wilhelm',0,8256)
 (1232,'The Prince','Machiavelli, Niccolò','Marriott, W. K. (William Kenaz)',0,8128)
 (2701,'Moby Dick; Or, The Whale','Melville, Herman','',0,7456)
 (76,'Adventures of Huckleberry Finn','Twain, Mark','Kemble, E. W. (Edward Windsor)',0,7253)
 (2600,'War and Peace','Tolstoy, Leo, graf','Maude, Aylmer;Maude, Louise',0,7122)
 (5200,'Metamorphosis','Kafka, Franz','Wyllie, David',0,6756)
 (1184,'The Count of Monte Cristo, Illustrated','Dumas, Alexandre','',0,5996)
 (1400,'Great Expectations','Dickens, Charles','',0,5804)
 (135,'Les Misérables','Hugo, Victor','Hapgood, Isabel Florence',0,5778)
 (16,'Peter Pan','Barrie, J. M. (James Matthew)','',0,5483)
 (844,'The Importance of Being Earnest: A Trivial Comedy for Serious People','Wilde, Oscar','',0,5227)
 (2500,'Siddhartha','Hesse, Hermann','',0,5205)
 (16328,'Beowulf: An Anglo-Saxon Epic Poem','','Hall, J. Lesslie (John Lesslie)',0,5078)
 (84,'Frankenstein; Or, The Modern Prometheus','Shelley, Mary Wollstonecraft','',0,5047)
 (1260,'Jane Eyre: An Autobiography','Brontë, Charlotte','Townsend, F. H. (Frederick Henry)',0,4527)
 (6130,'The Iliad','Homer','Pope, Alexander;Buckley, Theodore Alois',0,4179)
 (2554,'Crime and Punishment','Dostoyevsky, Fyodor','Garnett, Constance',0,3944)
 (2542,'A Doll&apos;s House : a play','Ibsen, Henrik','',0,3898)
 (768,'Wuthering Heights','Brontë, Emily','',0,3849)
 (28054,'The Brothers Karamazov','Dostoyevsky, Fyodor','',0,3833)
 (2814,'Dubliners','Joyce, James','',0,3783)
 (23,'Narrative of the Life of Frederick Douglass, an American Slave','Douglass, Frederick','',0,3767)
 (35,'The Time Machine','Wells, H. G. (Herbert George)','',0,3738)
 (244,'A Study in Scarlet','Doyle, Arthur Conan','',0,3689)
 (1497,'The Republic','Plato','Jowett, Benjamin',0,3639)
 (308,'Three Men in a Boat','Jerome, Jerome K. (Jerome Klapka)','',0,3454)
 (161,'Sense and Sensibility','Austen, Jane','',0,3452)
 (26184,'Simple Sabotage Field Manual','United States. Office of Strategic Services','',0,3414)
 (45,'Anne of Green Gables','Montgomery, L. M. (Lucy Maud)','',0,3337)
 (2680,'Meditations','Marcus Aurelius, Emperor of Rome','',0,3220)
 (4363,'Beyond Good and Evil','Nietzsche, Friedrich Wilhelm','Zimmern, Helen',0,3215)
 (829,'Gulliver&apos;s Travels into Several Remote Nations of the World','Swift, Jonathan','',0,3132)
 (1322,'Leaves of Grass','Whitman, Walt','',0,3077)
 (20203,'Autobiography of Benjamin Franklin','Franklin, Benjamin','Pine, Frank Woodworth;Smith, E. Boyd (Elmer Boyd)',0,3004)
 (1399,'Anna Karenina','Tolstoy, Leo, graf','Garnett, Constance',0,2972)
 (863,'The Mysterious Affair at Styles','Christie, Agatha','',0,2942)
 (2147,'The Works of Edgar Allan Poe — Volume 1','Poe, Edgar Allan','Willis, Nathaniel Parker;Lowell, James Russell',0,2930)
 (36,'The War of the Worlds','Wells, H. G. (Herbert George)','',0,2896)
 (996,'Don Quixote','Cervantes Saavedra, Miguel de','Ormsby, John',0,2862)
 (14264,'The Practice and Science of Drawing','Speed, Harold','',0,2830)
 (55,'The Wonderful Wizard of Oz','Baum, L. Frank (Lyman Frank)','',0,2759)
 (1112,'The Tragedy of Romeo and Juliet','Shakespeare, William','',0,2733)
 (8800,'The Divine Comedy by Dante, Illustrated','Dante Alighieri','Cary, Henry Francis;Doré, Gustave',0,2714)
 (205,'Walden, and On The Duty Of Civil Disobedience','Thoreau, Henry David','',0,2678)
 (3207,'Leviathan','Hobbes, Thomas','',0,2652)
 (10,'The King James Version of the Bible','','',0,2637)
 (521,'The Life and Adventures of Robinson Crusoe','Defoe, Daniel','',0,2635)
 (46,'A Christmas Carol in Prose; Being a Ghost Story of Christmas','Dickens, Charles','Leech, John',0,2606)
 (12,'Through the Looking-Glass','Carroll, Lewis','',0,2396)
 (141,'Mansfield Park','Austen, Jane','',0,2378)
 (730,'Oliver Twist','Dickens, Charles','',0,2375)
 (1998,'Thus Spake Zarathustra: A Book for All and None','Nietzsche, Friedrich Wilhelm','Common, Thomas',0,2298)
 (14591,'Faust','Goethe, Johann Wolfgang von','Taylor, Bayard;Clarke, Harry',0,2265)
 (583,'The Woman in White','Collins, Wilkie','',0,2233)
 (30601,'How to Analyze People on Sight Through the Science of Human Analysis: The Five Human Types','Benedict, Elsie Lincoln','Benedict, Ralph Paine',0,2190)
 (145,'Middlemarch','Eliot, George','',0,2176)
 (514,'Little Women','Alcott, Louisa May','',0,2159)
 (103,'Around the World in Eighty Days','Verne, Jules','',0,2125)
 (62,'A Princess of Mars','Burroughs, Edgar Rice','',0,1687)
 (3600,'Essays of Michel de Montaigne — Complete','Montaigne, Michel de','Cotton, Charles;Hazlitt, William Carew',0,2083)
 (766,'David Copperfield','Dickens, Charles','',0,2056)
 (2148,'The Works of Edgar Allan Poe — Volume 2','Poe, Edgar Allan','',0,2044)
 (34901,'On Liberty','Mill, John Stuart','',0,2014)
 (160,'The Awakening, and Selected Short Stories','Chopin, Kate','',0,1978)
 (38427,'The World as Will and Idea (Vol. 1 of 3)','Schopenhauer, Arthur','Haldane, R. B. Haldane (Richard Burdon Haldane), Viscount;Kemp, J. (John)',0,1942)
 (55200,'A Book About Words','Graham, George Frederick','',0,1938)
 (600,'Notes from the Underground','Dostoyevsky, Fyodor','',0,1907)
 (1727,'The Odyssey&#13; Rendered into English prose for the use of those who cannot read the original','Homer','Butler, Samuel',0,1871)
 (2097,'The Sign of the Four','Doyle, Arthur Conan','',0,1851)
 (33,'The Scarlet Letter','Hawthorne, Nathaniel','',0,1848)
 (55189,'The Summit House Mystery The Earthly Purgatory','Dougall, L. (Lily)','',0,1819)
 (815,'Democracy in America — Volume 1','Tocqueville, Alexis de','Reeve, Henry',0,1796)
 (1257,'The Three Musketeers','Dumas, Alexandre','',0,1785)
 (41,'The Legend of Sleepy Hollow','Irving, Washington','',0,1771)
 (61,'The Communist Manifesto','Engels, Friedrich','Marx, Karl',0,1758)
 (3296,'The Confessions of St. Augustine','Augustine, Saint, Bishop of Hippo','Pusey, E. B. (Edward Bouverie)',0,1733)
 (2000,'Don Quijote','Cervantes Saavedra, Miguel de','',0,1732)
 (86,'A Connecticut Yankee in King Arthur&apos;s Court','Twain, Mark','',0,1729)
 (55387,'One Hundred Proofs that the Earth is Not a Globe','Carpenter, William Boyd','',0,1702)
 (1155,'The Secret Adversary','Christie, Agatha','',0,1687)
 (215,'The Call of the Wild','London, Jack','',0,1676)
 (55242,'The Black Ghost of the Highway','Linnell, Gertrude','',0,1669)
 (289,'The Wind in the Willows','Grahame, Kenneth','',0,1658)
 (1251,'Le Morte d&apos;Arthur: Volume 1','Malory, Thomas, Sir','',0,1656)
 (209,'The Turn of the Screw','James, Henry','',0,1640)
 (25717,'The History of the Decline and Fall of the Roman Empire&#13; Table of Contents with links in the HTML file to the two Project Gutenberg editions (12 volumes)','Gibbon, Edward','Widger, David;Milman, Henry Hart',0,1568)
 (7849,'The Trial','Kafka, Franz','Wyllie, David',0,1567)
 (1524,'Hamlet, Prince of Denmark','Shakespeare, William','',0,1562)
 (121,'Northanger Abbey','Austen, Jane','',0,1561)
 (541,'The Age of Innocence','Wharton, Edith','',0,1490)
 (2413,'Madame Bovary','Flaubert, Gustave','Aveling, Eleanor Marx',0,1488)
 (408,'The Souls of Black Folk','Du Bois, W. E. B. (William Edward Burghardt)','',0,1480)
 (834,'The Memoirs of Sherlock Holmes','Doyle, Arthur Conan','',0,1476)
 (14838,'The Tale of Peter Rabbit','Potter, Beatrix','',0,1473)
 (779,'The Tragical History of Doctor Faustus&#13; From the Quarto of 1604','Marlowe, Christopher','Dyce, Alexander',0,1452)
 (1228,'On the Origin of Species By Means of Natural Selection&#13; Or, the Preservation of Favoured Races in the Struggle for Life','Darwin, Charles','',0,1436)
 (5000,'The Notebooks of Leonardo Da Vinci — Complete','Leonardo, da Vinci','Richter, Jean Paul',0,1436)
 (1080,'A Modest Proposal&#13; For preventing the children of poor people in Ireland, from being a burden on their parents or country, and for making them beneficial to the publick','Swift, Jonathan','',0,1429)
 (31547,'Youth','Asimov, Isaac','',0,1395)
 (7370,'Second Treatise of Government','Locke, John','',0,1383)
 (902,'The Happy Prince, and Other Tales','Wilde, Oscar','',0,1380)
 (78,'Tarzan of the Apes','Burroughs, Edgar Rice','',0,972)
 (37134,'The Elements of Style','Strunk, William','',0,1368)
 (5739,'Korean—English Dictionary','Kuperman, Leon','',0,1357)
 (3300,'An Inquiry into the Nature and Causes of the Wealth of Nations','Smith, Adam','',0,1341)
 (21279,'2 B R 0 2 B','Vonnegut, Kurt','',0,1341)
 (4280,'The Critique of Pure Reason','Kant, Immanuel','Meiklejohn, J. M. D. (John Miller Dow)',0,1337)
 (10007,'Carmilla','Le Fanu, Joseph Sheridan','',0,1331)
 (786,'Hard Times','Dickens, Charles','',0,1330)
 (851,'Narrative of the Captivity and Restoration of Mrs. Mary Rowlandson','Rowlandson, Mary White','',0,1327)
 (1023,'Bleak House','Dickens, Charles','',0,1327)
 (3825,'Pygmalion','Shaw, Bernard','',0,1325)
 (4276,'North and South','Gaskell, Elizabeth Cleghorn','',0,1311)
 (2130,'Utopia','More, Thomas, Saint','Morley, Henry',0,1297)
 (1695,'The Man Who Was Thursday: A Nightmare','Chesterton, G. K. (Gilbert Keith)','',0,1286)
 (8492,'The King in Yellow','Chambers, Robert W. (Robert William)','',0,1286)
 (140,'The Jungle','Sinclair, Upton','',0,1280)
 (55201,'The Republic of Plato','Plato','Jowett, Benjamin',0,1276)
 (2264,'Macbeth','Shakespeare, William','',0,1276)
 (1837,'The Prince and the Pauper','Twain, Mark','',0,1276)
 (203,'Uncle Tom&apos;s Cabin','Stowe, Harriet Beecher','',0,1257)
 (55199,'The True Travels, Adventures, and Observations of Captain John Smith into Europe, Asia, Africa, and America From Ann. Dom. 1593 to 1629','Smith, John Bernhard','',0,1238)
 (16643,'Essays by Ralph Waldo Emerson','Emerson, Ralph Waldo','Turpin, Edna Henry Lee',0,1210)
 (55243,'The Puzzle in the Pond Judy Bolton Series, #34','Sutton, Margaret','',0,1204)
 (51,'Anne of the Island','Montgomery, L. M. (Lucy Maud)','',0,1204)
 (4367,'Personal Memoirs of U. S. Grant, Complete','Grant, Ulysses S. (Ulysses Simpson)','',0,1200)
 (2638,'The Idiot','Dostoyevsky, Fyodor','Martin, Eva M.',0,1196)
 (8164,'My Man Jeeves','Wodehouse, P. G. (Pelham Grenville)','',0,1195)
 (139,'The Lost World','Doyle, Arthur Conan','',0,1185)
 (18251,'Latin for Beginners','D&apos;Ooge, Benjamin L. (Benjamin Leonard)','',0,1184)
 (503,'The Blue Fairy Book','Lang, Andrew','',0,783)
 (3176,'The Innocents Abroad','Twain, Mark','',0,1170)
 (155,'The Moonstone','Collins, Wilkie','',0,1162)
 (8789,'The vision of hell. &#13; By Dante Alighieri.&#13; Translated by Rev. Henry Francis Cary, M.A.&#13; and illustrated with the seventy-five designs of Gustave Doré.','Dante Alighieri','Cary, Henry Francis;Doré, Gustave',0,1159)
 (852,'Democracy and Education: An Introduction to the Philosophy of Education','Dewey, John','',0,1159)
 (5827,'The Problems of Philosophy','Russell, Bertrand','',0,1156)
 (805,'This Side of Paradise','Fitzgerald, F. Scott (Francis Scott)','',0,1154)
 (55257,'At Close Range','Smith, Francis Hopkinson','',0,1139)
 (421,'Kidnapped','Stevenson, Robert Louis','',0,1130)
 (29558,'Boy Scouts Handbook The First Edition, 1911','Boy Scouts of America','',0,1125)
 (1250,'Anthem','Rand, Ayn','',0,1120)
 (3090,'Complete Original Short Stories of Guy De Maupassant','Maupassant, Guy de','Quesada, Louise Charlotte Garstin;Henderson, A. E.;McMaster, Albert Cohn',0,1119)
 (22381,'Myths and Legends of Ancient Greece and Rome','Berens, E. M.','',0,1118)
 (55262,'Psychology Briefer Course','James, William','',0,1106)
 (131,'The Pilgrim&apos;s Progress from this world to that which is to come&#13; Delivered under the similitude of a dream, by John Bunyan','Bunyan, John','',0,1106)
 (21839,'Sense and Sensibility','Austen, Jane','Dobson, Austin;Thomson, Hugh',0,1093)
 (25141,'The Pursuit of God','Tozer, A. W. (Aiden Wilson)','',0,1092)
 (82,'Ivanhoe: A Romance','Scott, Walter','',0,1087)
 (3186,'The Mysterious Stranger, and Other Stories','Twain, Mark','',0,1086)
 (6519,'Songs of Kabir','Kabir','Tagore, Rabindranath',0,1081)
 (13437,'Best Russian Short Stories','','Garshin, Vsevolod Mikhailovich;Dostoyevsky, Fyodor;Turgenev, Ivan Sergeevich;Artsybashev, M. (Mikhail);Kuprin, A. I. (Aleksandr Ivanovich);Tolstoy, Leo, graf;Chekhov, Anton Pavlovich;Potapenko, Ignatii Nicholaevich;Saltykov, Mikhail Evgrafovich;Korolenko, Vladimir Galaktionovich;Gogol, Nikolai Vasilevich;Andreyev, Leonid;Semenov, S. T. (Sergei Terentyevich);Sologub, Fyodor;Seltzer, Thomas;Gorky, Maksim;Pushkin, Aleksandr Sergeevich',0,1080)
 (13415,'The Lady with the Dog and Other Stories','Chekhov, Anton Pavlovich','Garnett, Constance',0,1075)
 (47,'Anne of Avonlea','Montgomery, L. M. (Lucy Maud)','',0,1056)
 (4517,'Ethan Frome','Wharton, Edith','',0,1055)
 (2383,'The Canterbury Tales, and Other Poems','Chaucer, Geoffrey','Purves, David Laing',0,1043)
 (4217,'A Portrait of the Artist as a Young Man','Joyce, James','',0,1037)
 (159,'The Island of Doctor Moreau','Wells, H. G. (Herbert George)','',0,1032)
 (4240,'Women in Love','Lawrence, D. H. (David Herbert)','',0,1026)
 (7142,'The History of the Peloponnesian War','Thucydides','Crawley, Richard',0,1023)
 (55378,'Miss Mephistopheles A Novel, (Sequel to Madame Midas.)','Hume, Fergus','',0,1018)
 (10947,'The Best American Humorous Short Stories','','Stockton, Frank Richard;Johnston, Richard Malcolm;Bunner, H. C. (Henry Cuyler);Leslie, Eliza;Hale, Edward Everett;Twain, Mark;Harte, Bret;Henry, O.;Hastings, Wells;Poe, Edgar Allan;Chester, George Randolph;Jessup, Alexander;Kirkland, Caroline M. (Caroline Matilda);Lampton, William James;Holmes, Oliver Wendell;Curtis, George William;Morris, George Pope;Edwards, Harry Stillwell;Cooke, Grace MacGowan',0,1018)
 (15250,'Myths and Legends of China','Werner, E. T. C. (Edward Theodore Chalmers)','',0,1013)
 (55381,'After the War: A Southern Tour May 1, 1865 to May 1, 1866','Reid, Whitelaw','',0,1012)
 (55346,'Lectures on Painting Delivered to the students of the Royal Acadamy','Armitage, Edward','',0,1005)
 (910,'White Fang','London, Jack','',0,1004)
 (4093,'Hedda Gabler','Ibsen, Henrik','Archer, William;Gosse, Edmund',0,1000)
 (55404,'The Man with a Secret A Novel','Hume, Fergus','',0,996)
 (5230,'The Invisible Man: A Grotesque Romance','Wells, H. G. (Herbert George)','',0,990)
 (19322,'The Antichrist','Nietzsche, Friedrich Wilhelm','Mencken, H. L. (Henry Louis)',0,989)
 (204,'The Innocence of Father Brown','Chesterton, G. K. (Gilbert Keith)','',0,987)
 (24518,'Memoirs of Extraordinary Popular Delusions and the Madness of Crowds','Mackay, Charles','',0,983)
 (55219,'The Prose Tales of Alexander Pushkin','Pushkin, Alexander','Keane, Thomas',0,983)
 (55220,'Five Acres too Much','Roosevelt, Robert Barnwell','',0,980)
 (10609,'English Literature&#13; Its History and Its Significance for the Life of the English-Speaking World','Long, William J. (William Joseph)','',0,979)
 (731,'History of the Decline and Fall of the Roman Empire — Volume 1','Gibbon, Edward','Milman, Henry Hart',0,974)
 (2781,'Just So Stories','Kipling, Rudyard','',0,973)
 (55230,'The Day After Death (New Edition) Our Future Life According to Science','Figuier, Louis','',0,973)
 (2527,'The Sorrows of Young Werther','Goethe, Johann Wolfgang von','Boylan, R. Dillon',0,969)
 (7452,'Autobiography of a Yogi','Yogananda, Paramahansa','',0,961)
 (28233,'Philosophiae Naturalis Principia Mathematica','Newton, Isaac, Sir','',0,958)
 (55222,'Misunderstood','Montgomery, Florence','',0,954)
 (2610,'Notre-Dame De Paris','Hugo, Victor','Hapgood, Isabel Florence',0,950)
 (55309,'The Crimson Cryptogram A Detective Story','Hume, Fergus','',0,947)
 (15474,'The Mahabharata of Krishna-Dwaipayana Vyasa, Volume 1 Books 1, 2 and 3','','Ganguli, Kisari Mohan',0,947)
 (375,'An Occurrence at Owl Creek Bridge','Bierce, Ambrose','',0,934)
 (30241,'The Person and Work of The Holy Spirit','Torrey, R. A. (Reuben Archer)','',0,934)
 (18857,'A Journey to the Centre of the Earth','Verne, Jules','',0,932)
 (21700,'Don Juan','Byron, George Gordon Byron, Baron','',0,929)
 (55221,'The Battle of the Marne','Perris, George Herbert','',0,922)
 (28885,'Alice&apos;s Adventures in Wonderland Illustrated by Arthur Rackham. With a Proem by Austin Dobson','Carroll, Lewis','Rackham, Arthur',0,918)
 (7178,'Swann&apos;s Way','Proust, Marcel','Scott-Moncrieff, C. K. (Charles Kenneth)',0,917)
 (972,'The Devil&apos;s Dictionary','Bierce, Ambrose','',0,916)
 (45109,'The Enchiridion','Epictetus','Higginson, Thomas Wentworth',0,908)
 (932,'The Fall of the House of Usher','Poe, Edgar Allan','',0,905)
 (45410,'Composition','Dow, Arthur W. (Arthur Wesley)','',0,900)
 (55335,'The Mercer Boys&apos; Cruise in the Lassie','Wyckoff, Capwell','',0,893)
 (22367,'Die Verwandlung','Kafka, Franz','',0,892)
 (64,'The Gods of Mars','Burroughs, Edgar Rice','',0,490)
 (55285,'Lives of Famous London Beggars With Forty Portraits of the Most Remarkable.','Smith, John Thomas','',0,889)
 (35461,'A Short History of the World','Wells, H. G. (Herbert George)','',0,889)
 (5001,'Relativity : the Special and General Theory','Einstein, Albert','Lawson, Robert W. (Robert William)',0,888)
 (55336,'From Job to Job around the World','Fletcher, Alfred Charles Ben','',0,884)
 (10554,'Right Ho, Jeeves','Wodehouse, P. G. (Pelham Grenville)','',0,882)
 (3800,'Ethics','Spinoza, Benedictus de','Elwes, R. H. M. (Robert Harvey Monro)',0,877)
 (885,'An Ideal Husband','Wilde, Oscar','',0,874)
 (68,'Warlord of Mars','Burroughs, Edgar Rice','',0,467)
 (15,'Moby Dick','Melville, Herman','',0,866)
 (55214,'The Village of Hide and Seek','Wilson, Bingham Thoburn','Dunton, W. Herbert',0,865)
 (23700,'The Decameron of Giovanni Boccaccio','Boccaccio, Giovanni','Payne, John',0,865)
 (921,'De Profundis','Wilde, Oscar','',0,862)
 (245,'Life on the Mississippi','Twain, Mark','',0,857)
 (2892,'Irish Fairy Tales','Stephens, James','Rackham, Arthur',0,855)
 (55368,'Nazi Conspiracy and Aggression (Vol. I)','Various','',0,848)
 (580,'The Pickwick Papers','Dickens, Charles','',0,848)
 (8799,'The Divine Comedy by Dante, Illustrated, Paradise, Complete','Dante Alighieri','Doré, Gustave;Cary, Henry Francis',0,847)
 (55350,'Counterfeit Money The "green goods" business exposed for the benefit of all who have dishonest inclinations.','Anonymous','',0,846)
 (55249,'Daniel Boone, Backwoodsman','Forbes-Lindsay, C. H.','McKernan, Frank',0,844)
 (10625,'A Concise Dictionary of Middle English from A.D. 1150 to 1580','Skeat, Walter W. (Walter William)','Mayhew, A. L. (Anthony Lawson)',0,837)
 (15489,'Dream Psychology: Psychoanalysis for Beginners','Freud, Sigmund','Eder, M. D. (Montague David);Tridon, André',0,833)
 (148,'The Autobiography of Benjamin Franklin','Franklin, Benjamin','Eliot, Charles William',0,833)
 (55247,'Night Operations For Infantry Compiled for the Use of Company Officers','Dawkins, Charles Tyrwhitt','',0,831)
 (18269,'Pascal&apos;s Pensées','Pascal, Blaise','Eliot, T. S. (Thomas Stearns)',0,829)
 (1656,'Apology','Plato','Jowett, Benjamin',0,822)
 (5131,'Childe Harold&apos;s Pilgrimage','Byron, George Gordon Byron, Baron','',0,821)
 (55244,'The Prophet&apos;s Mantle','Nesbit, E. (Edith)','Bland, Hubert',0,821)
 (4705,'A Treatise of Human Nature','Hume, David','',0,818)
 (3155,'She','Haggard, H. Rider (Henry Rider)','',0,816)
 (696,'The Castle of Otranto','Walpole, Horace','Morley, Henry',0,814)
 (110,'Tess of the d&apos;Urbervilles: A Pure Woman','Hardy, Thomas','',0,813)
 (242,'My Antonia','Cather, Willa','',0,810)
 (3177,'Roughing It','Twain, Mark','',0,808)
 (1321,'The Waste Land','Eliot, T. S. (Thomas Stearns)','',0,801)
 (55359,'The Mystery Crash Sky Scout Series, #1','Powell, Ardon Van Buren','',0,795)
 (2166,'King Solomon&apos;s Mines','Haggard, H. Rider (Henry Rider)','',0,791)
 (2265,'Hamlet','Shakespeare, William','',0,791)
 (389,'The Great God Pan','Machen, Arthur','',0,789)
 (6737,'The Social Cancer: A Complete English Version of Noli Me Tangere','Rizal, José','Derbyshire, Charles E.',0,788)
 (55185,'Some Principles of Frontier Mountain Warfare','Bird, W. D. (Wilkinson Dent)','',0,786)
 (34811,'Buddenbrooks: Verfall einer Familie','Mann, Thomas','',0,785)
 (974,'The Secret Agent: A Simple Tale','Conrad, Joseph','',0,785)
 (81,'The Return of Tarzan','Burroughs, Edgar Rice','',0,380)
 (11339,'Aesop&apos;s Fables; a new translation','Aesop','Rackham, Arthur;Vernon Jones, V. S. (Vernon Stanley);Chesterton, G. K. (Gilbert Keith)',0,777)
 (55263,'Thirteen Years of a Busy Woman&apos;s Life','Tweedie, Mrs. Alec','',0,774)
 (32032,'Second Variety','Dick, Philip K.','Ebel, Alex',0,774)
 (31,'Plays of Sophocles: Oedipus the King; Oedipus at Colonus; Antigone','Sophocles','Storr, Francis',0,772)
 (55270,'The Ways of Life Two Stories','Oliphant, Mrs. (Margaret)','',0,767)
 (5720,'A Shropshire Lad','Housman, A. E. (Alfred Edward)','',0,767)
 (2397,'The Story of My Life&#13; With her letters (1887-1901) and a supplementary account of her education, including passages from the reports and letters of her teacher, Anne Mansfield Sullivan, by John Albert Macy','Keller, Helen','Macy, John Albert;Sullivan, Annie',0,762)
 (2229,'Faust: Der Tragödie erster Teil','Goethe, Johann Wolfgang von','',0,758)
 (599,'Vanity Fair','Thackeray, William Makepeace','',0,757)
 (2641,'A Room with a View','Forster, E. M. (Edward Morgan)','',0,755)
 (55217,'Making His Mark','Alger, Horatio, Jr.','Mason, Robert L.',0,751)
 (29765,'Webster&apos;s Unabridged Dictionary','Various','',0,750)
 (7128,'Indian Fairy Tales','','Jacobs, Joseph;Batten, John Dickson',0,749)
 (55343,'Ambassador Morgenthau&apos;s Story','Morgenthau, Henry','',0,749)
 (55298,'Her Husband&apos;s Purse','Martin, Helen R.','Howitt, John Newton',0,749)
 (1974,'The Poetics of Aristotle','Aristotle','Butcher, S. H. (Samuel Henry)',0,748)
 (1946,'On War — Volume 1','Clausewitz, Carl von','Graham, J. J. (James John)',0,748)
 (3623,'The Golden Bough: A Study of Magic and Religion','Frazer, James George','',0,746)
 (55268,'How it Flies or, Conquest of the Air The Story of Man&apos;s Endeavors to Fly and of the Inventions by which He Has Succeeded','Ferris, Richard','',0,745)
 (500,'The Adventures of Pinocchio','Collodi, Carlo','Della Chiesa, Carol',0,742)
 (8117,'The Possessed (The Devils)','Dostoyevsky, Fyodor','Garnett, Constance',0,742)
 (55374,'Frank Reade, Jr., Fighting the Terror of the Coast','Senarens, Luis','',0,742)
 (683,'The Compleat Angler','Walton, Izaak','',0,738)
 (2149,'The Works of Edgar Allan Poe — Volume 3','Poe, Edgar Allan','',0,733)
 (8438,'The Ethics of Aristotle','Aristotle','',0,733)
 (1153,'The Chessmen of Mars','Burroughs, Edgar Rice','',0,331)
 (45631,'Twelve Years a Slave&#13; Narrative of Solomon Northup, a Citizen of New-York, Kidnapped in Washington City in 1841, and Rescued in 1853, from a Cotton Plantation near the Red River in Louisiana','Northup, Solomon','',0,730)
 (55382,'Field Book of Common Rocks and Minerals For identifying the Rocks and Minerals of the United States and interpreting their Origins and Meanings','Corbin, Walter Everett','Loomis, Frederic Brewster',0,729)
 (558,'The Thirty-Nine Steps','Buchan, John','',0,728)
 (55317,'The Meditations of the Emperor Marcus Aurelius Antoninus A new rendering based on the Foulis translation of 1742','Aurelius, Marcus','Chrystal, George',0,726)
 (55353,'Boys Who Became Famous Men Stories of the Childhood of Poets, Artists, and Musicians','Skinner, Harriet Pearl','Gallagher, Sears',0,726)
 (17192,'The Raven','Poe, Edgar Allan','Doré, Gustave;Stedman, Edmund Clarence',0,725)
 (55283,'The Bet and other stories','Chekhov, Anton Pavlovich','Murry, John Middleton;Koteliansky, S. S. (Samuel Solomonovitch)',0,723)
 (50133,'The Dunwich Horror','Lovecraft, H. P. (Howard Phillips)','',0,719)
 (544,'Anne&apos;s House of Dreams','Montgomery, L. M. (Lucy Maud)','',0,719)
 (55314,'The English Housekeeper Or, Manual of Domestic Management: Containing advice on the conduct of household affairs and practical instructions','Cobbett, Anne','',0,718)
 (55274,'The Wind-Jammers','Hains, T. Jenkins (Thornton Jenkins)','',0,718)
 (55179,'One of The Six Hundred','Grant, James, archaeologist','',0,715)
 (55183,'Satan A Romance of the Bahamas','Stacpoole, H. De Vere (Henry De Vere)','',0,714)
 (55195,'The Historians&apos; History of the World in Twenty-Five Volumes, Volume 3 Greece to the Peloponnesian War','Various','Williams, Henry Smith',0,712)
 (14328,'The Consolation of Philosophy','Boethius','James, H. R. (Henry Rosher)',0,712)
 (19994,'The Aesop for Children&#13; With pictures by Milo Winter','Aesop','Winter, Milo',0,707)
 (31469,'The Shunned House','Lovecraft, H. P. (Howard Phillips)','',0,706)
 (28644,'Beyond the Door','Dick, Philip K.','',0,706)
 (72,'Thuvia, Maid of Mars','Burroughs, Edgar Rice','',0,306)
 (12228,'Home Geography for Primary Grades','Long, C. C.','',0,698)
 (48320,'Adventures of Sherlock Holmes Illustrated','Doyle, Arthur Conan','',0,697)
 (55212,'Why Frau Fromann Raised her Prices and other stories','Trollope, Anthony','',0,697)
 (12116,'Struwwelpeter: Merry Stories and Funny Pictures','Hoffmann, Heinrich','',0,697)
 (2707,'The History of Herodotus — Volume 1','Herodotus','Macaulay, G. C. (George Campbell)',0,693)
 (20781,'Heidi (Gift Edition)','Spyri, Johanna','Stork, Elisabeth P. (Elisabeth Pausinger);Kirk, Maria Louise',0,691)
 (20239,'The Ten Books on Architecture','Vitruvius Pollio','',0,691)
 (4507,'As a Man Thinketh','Allen, James','',0,690)
 (2499,'Siddhartha: eine indische Dichtung','Hesse, Hermann','',0,689)
 (10800,'The Anatomy of Melancholy','Burton, Robert','',0,688)
 (55390,'Triumphs and Wonders of the 19th Century The True Mirror of a Phenomenal Era','Boyd, James P. (James Penny)','',0,687)
 (1200,'Gargantua and Pantagruel','Rabelais, François','Motteux, Peter Anthony;Urquhart, Thomas, Sir;Doré, Gustave',0,686)
 (55339,'The Lawton Girl','Frederic, Harold','',0,685)
 (8581,'The Art of Money Getting; Or, Golden Rules for Making Money','Barnum, P. T. (Phineas Taylor)','',0,684)
 (1079,'The Life and Opinions of Tristram Shandy, Gentleman','Sterne, Laurence','',0,684)
 (42671,'Pride and Prejudice','Austen, Jane','Chapman, R. W. (Robert William)',0,683)
 (55228,'Notes on the New Testament Explanatory and Practical','Barnes, Albert','Frew, Robert',0,681)
 (146,'A Little Princess&#13; Being the whole story of Sara Crewe now told for the first time','Burnett, Frances Hodgson','',0,680)
 (4018,'Japanese Fairy Tales','Ozaki, Yei Theodora','',0,678)
 (10897,'The Wendigo','Blackwood, Algernon','',0,677)
 (55403,'The Petrol Engine A Text-book dealing with the Principles of Design and Construction, with a Special Chapter on the Two-stroke Engine','Kean, Francis John','',0,677)
 (10676,'The Reign of Greed','Rizal, José','Derbyshire, Charles E.',0,675)
 (38485,'Ancient Pagan and Modern Christian Symbolism&#13; With an Essay on Baal Worship, on the Assyrian Sacred "Grove," and Other Allied Symbols','Inman, Thomas','Newton, John, M.R.C.S.E.',0,665)
 (4081,'The Alchemist','Jonson, Ben','',0,663)
 (7205,'Also sprach Zarathustra: Ein Buch für Alle und Keinen','Nietzsche, Friedrich Wilhelm','',0,662)
 (55237,'The Senator&apos;s Favorite','Miller, Alex. McVeigh, Mrs.','',0,662)
 (271,'Black Beauty','Sewell, Anna','',0,661)
 (175,'The Phantom of the Opera','Leroux, Gaston','',0,660)
 (1754,'The Sea-Gull','Chekhov, Anton Pavlovich','',0,660)
 (201,'Flatland: A Romance of Many Dimensions (Illustrated)','Abbott, Edwin Abbott','',0,660)
 (2350,'His Last Bow: An Epilogue of Sherlock Holmes','Doyle, Arthur Conan','',0,657)
 (17161,'Max und Moritz: Eine Bubengeschichte in sieben Streichen','Busch, Wilhelm','',0,655)
 (35123,'The Ladies&apos; Book of Etiquette, and Manual of Politeness A Complete Hand Book for the Use of the Lady in Polite Society','Hartley, Florence','',0,650)
 (55246,'Yorkshire Vales and Wolds','Home, Gordon','',0,650)
 (9622,'Lyrical Ballads, With a Few Other Poems (1798)','Coleridge, Samuel Taylor','Wordsworth, William',0,649)
 (55206,'Fábulas','Samaniego, Félix','',0,648)
 (55275,'Indian Fights and Fighters: The Soldier and the Sioux','Brady, Cyrus Townsend','',0,648)
 (228,'The Aeneid','Virgil','Dryden, John',0,647)
 (15143,'Famous Modern Ghost Stories','','Freeman, Mary Eleanor Wilkins;Harvey, William Fryer;Machen, Arthur;Blackwood, Algernon;Maupassant, Guy de;Andreyev, Leonid;Bierce, Ambrose;Le Gallienne, Richard;Poe, Edgar Allan;Steele, Wilbur Daniel;Closser, Myla Jo;Scarborough, Dorothy;Chambers, Robert W. (Robert William);Dunbar, Olivia Howard;France, Anatole;O&apos;Brien, Fitz James',0,645)
 (31516,'The Eyes Have It','Dick, Philip K.','',0,644)
 (11231,'Bartleby, the Scrivener: A Story of Wall-Street','Melville, Herman','',0,644)
 (85,'The Beasts of Tarzan','Burroughs, Edgar Rice','',0,242)
 (55258,'Tom Terror, the Outlaw','Jackson, James Grey','',0,642)
 (2151,'The Works of Edgar Allan Poe — Volume 5','Poe, Edgar Allan','',0,640)
 (55287,'The Price of Coal A Play','Brighouse, Harold','',0,638)
 (16317,'The Art of Public Speaking','Esenwein, J. Berg (Joseph Berg)','Carnegie, Dale',0,637)
 (106,'Jungle Tales of Tarzan','Burroughs, Edgar Rice','',0,236)
 (14522,'The Canterville Ghost','Wilde, Oscar','Goldsmith, Wallace',0,635)
 (946,'Lady Susan','Austen, Jane','',0,634)
 (90,'The Son of Tarzan','Burroughs, Edgar Rice','',0,234)
 (963,'Little Dorrit','Dickens, Charles','',0,634)
 (55323,'Garryowen','Stacpoole, H. De Vere (Henry De Vere)','',0,633)
 (24869,'The Rámáyan of Válmíki, translated into English verse','Valmiki','Griffith, Ralph T. H. (Ralph Thomas Hotchkin)',0,632)
 (6124,'Pamela, or Virtue Rewarded','Richardson, Samuel','',0,632)
 (15399,'The Interesting Narrative of the Life of Olaudah Equiano, Or Gustavus Vassa, The African Written By Himself','Equiano, Olaudah','',0,632)
 (55409,'An Account of the Danes and Norwegians in England, Scotland, and Ireland','Worsaae, Jens Jakob Asmussen','',0,631)
 (55320,'The Voyage of the Arrow To the China Seas. Its Adventures and Perils, Including Its Capture by Sea Vultures from the Countess of Warwick, as set down by William Gore, Chief Mate','Hains, T. Jenkins (Thornton Jenkins)','Edwards, H. C. (Harry C.)',0,630)
 (540,'The Red Fairy Book','','Lang, Andrew',0,229)
 (59,'Discourse on the Method of Rightly Conducting One&apos;s Reason and of Seeking Truth in the Sciences','Descartes, René','Veitch, John',0,629)
 (55238,'Italian Yesterdays, vol. 1','Fraser, Hugh, Mrs.','',0,627)
 (55256,'The Story of a Donkey&#13; abridged from the French of Madame la comtesse de Ségur','Ségur, Sophie, comtesse de','Welsh, Charles',0,627)
 (55327,'Over The Border A Romance','Barr, Robert','',0,627)
 (1430,'Beautiful Stories from Shakespeare','Nesbit, E. (Edith)','Shakespeare, William',0,625)
 (551,'The Land That Time Forgot','Burroughs, Edgar Rice','',0,225)
 (9105,'Reflections; or Sentences and Moral Maxims','La Rochefoucauld, François duc de','Willis Bund, J. W. (John William);Friswell, J. Hain (James Hain)',0,624)
 (3743,'The Writings of Thomas Paine — Volume 4 (1794-1796): The Age of Reason','Paine, Thomas','Conway, Moncure Daniel',0,623)
 (854,'A Woman of No Importance','Wilde, Oscar','',0,620)
 (12242,'Poems by Emily Dickinson, Three Series, Complete','Dickinson, Emily','',0,619)
 (6087,'The Vampyre; a Tale','Polidori, John William','',0,618)
 (55226,'Superior Fishing','Roosevelt, Robert Barnwell','',0,615)
 (605,'Pellucidar','Burroughs, Edgar Rice','',0,215)
 (940,'The Last of the Mohicans; A narrative of 1757','Cooper, James Fenimore','',0,612)
 (2009,'The Origin of Species by Means of Natural Selection&#13; Or, the Preservation of Favoured Races in the Struggle for Life, 6th Edition','Darwin, Charles','',0,610)
 (1001,'Divine Comedy, Longfellow&apos;s Translation, Hell','Dante Alighieri','Longfellow, Henry Wadsworth',0,609)
 (967,'Nicholas Nickleby','Dickens, Charles','',0,608)
 (31100,'The Complete Project Gutenberg Works of Jane Austen A Linked Index of all PG Editions of Jane Austen','Austen, Jane','Widger, David',0,607)
 (883,'Our Mutual Friend','Dickens, Charles','',0,607)
 (2428,'An Essay on Man; Moral Essays and Satires','Pope, Alexander','Morley, Henry',0,606)
 (39293,'The Gentlemen&apos;s Book of Etiquette and Manual of Politeness&#13; Being a Complete Guide for a Gentleman&apos;s Conduct in All His Relations Towards Society','Hartley, Cecil B.','',0,599)
 (34206,'The Thousand and One Nights, Vol. I. Commonly Called the Arabian Nights&apos; Entertainments','','Harvey, William;Lane-Poole, Stanley;Poole, Edward Stanley;Lane, Edward William',0,598)
 (92,'Tarzan and the Jewels of Opar','Burroughs, Edgar Rice','',0,196)
 (284,'The House of Mirth','Wharton, Edith','',0,594)
 (18442,'Fifty Famous Stories Retold','Baldwin, James','',0,592)
 (2850,'The Wars of the Jews; Or, The History of the Destruction of Jerusalem','Josephus, Flavius','Whiston, William',0,591)
 (55279,'Latest Magic Being original conjuring tricks','Hoffmann, Professor','',0,591)
 (71,'On the Duty of Civil Disobedience','Thoreau, Henry David','',0,591)
 (55373,'The Story of Westminster Abbey','Brooke-Hunt, Violet','',0,590)
 (55266,'The Art of Glass-Blowing Plain Instruction for the Making of Chemical and Philosophical Instruments Which are Formed of Glass','Danger, T. P.','',0,590)
 (2020,'Tarzan the Terrible','Burroughs, Edgar Rice','',0,190)
 (11000,'An Old Babylonian Version of the Gilgamesh Epic','Jastrow, Morris','Clay, Albert Tobias',0,588)
 (1401,'Tarzan the Untamed','Burroughs, Edgar Rice','',0,187)
 (621,'The Varieties of Religious Experience: A Study in Human Nature','James, William','',0,584)
 (20480,'Palmistry for All','Cheiro','',0,579)
 (8525,'Eve&apos;s Diary, Complete','Twain, Mark','Ralph, Lester',0,579)
 (1122,'The Tragedy of Hamlet, Prince of Denmark','Shakespeare, William','',0,578)
 (40580,'A General History of the Pyrates:&#13; from their first rise and settlement in the island of Providence, to the present time','Defoe, Daniel','',0,575)
 (60,'The Scarlet Pimpernel','Orczy, Emmuska Orczy, Baroness','',0,575)
 (55276,'Twilight','Frankau, Julia','',0,573)
 (969,'The Tenant of Wildfell Hall','Brontë, Anne','Ward, Humphry, Mrs.',0,572)
 (512,'Mosses from an Old Manse, and Other Stories','Hawthorne, Nathaniel','',0,572)
 (12753,'The Legends of King Arthur and His Knights','Knowles, James, Sir','Speed, Lancelot;Malory, Thomas, Sir',0,572)
 (55254,'Fort Sumter: Anvil of War','Service, National Park','',0,572)
 (2759,'The Man in the Iron Mask','Dumas, Alexandre','',0,571)
 (22657,'Steam, Its Generation and Use','Babcock &amp; Wilcox Company','',0,567)
 (552,'The People That Time Forgot','Burroughs, Edgar Rice','',0,167)
 (640,'The Yellow Fairy Book','Lang, Andrew','',0,166)
 (55354,'What Does History Teach? Two Edinburgh Lectures','Blackie, John Stuart','',0,566)
 (149,'The Lost Continent','Burroughs, Edgar Rice','',0,165)
 (2150,'The Works of Edgar Allan Poe — Volume 4','Poe, Edgar Allan','',0,565)
 (6762,'Politics: A Treatise on Government','Aristotle','Ellis, William',0,564)
 (55234,'The Life of La Fayette The Knight of Liberty in Two Worlds and Two Centuries','Farmer, Lydia Hoyt','',0,564)
 (10814,'Legends, Tales and Poems','Bécquer, Gustavo Adolfo','Olmsted, Everett Ward',0,563)
 (20776,'Encyclopedia of Needlework','Dillmont, Thérèse de','',0,563)
 (55213,'The Girl Scouts at Miss Allen&apos;s School','Lavell, Edith','',0,563)
 (5402,'1811 Dictionary of the Vulgar Tongue','Grose, Francis','',0,561)
 (96,'The Monster Men','Burroughs, Edgar Rice','',0,159)
 (7213,'My Life and Work','Ford, Henry','',0,559)
 (2274,'How to Live on 24 Hours a Day','Bennett, Arnold','',0,555)
 (25807,'Poemas','Poe, Edgar Allan','Lasplaces, Alberto;Darío, Rubén;Pérez Bonalde, Juan Antonio;Torres, Carlos Arturo',0,555)
 (55300,'Society As I Have Found It','McAllister, Ward','',0,555)
 (981,'Beowulf','','Gummere, Francis Barton',0,553)
 (1041,'Shakespeare&apos;s Sonnets','Shakespeare, William','',0,552)
 (1567,'Poems','Eliot, T. S. (Thomas Stearns)','',0,551)
 (26654,'Peter and Wendy','Barrie, J. M. (James Matthew)','Bedford, F. D.',0,549)
 (1376,'The Little White Bird; Or, Adventures in Kensington Gardens','Barrie, J. M. (James Matthew)','',0,547)
 (55392,'Mackinac and Lake Stories','Catherwood, Mary Hartwell','',0,547)
 (12108,'Der Tod in Venedig','Mann, Thomas','',0,546)
 (10002,'The House on the Borderland','Hodgson, William Hope','',0,545)
 (38145,'Human, All Too Human: A Book for Free Spirits','Nietzsche, Friedrich Wilhelm','Harvey, Alexander',0,545)
 (2529,'The Analysis of Mind','Russell, Bertrand','',0,545)
 (553,'Out of Time&apos;s Abyss','Burroughs, Edgar Rice','',0,144)
 (2833,'The Portrait of a Lady — Volume 1','James, Henry','',0,543)
 (55386,'The Girl Scouts on the Ranch','Lavell, Edith','',0,542)
 (55269,'A Description of the Famous Kingdome of Macaria Shewing its Excellent Government: Wherein The Inhabitants Live in Great Prosperity, Health and Happinesse; the King Obeyed, the','Plattes, Gabriel','Hartlib, Samuel;Constable, Francis',0,541)
 (5657,'The Practice of the Presence of God','Lawrence, of the Resurrection, Brother','',0,540)
 (2242,'A Midsummer Night&apos;s Dream','Shakespeare, William','',0,540)
 (223,'The Wisdom of Father Brown','Chesterton, G. K. (Gilbert Keith)','',0,540)
 (12956,'A History of Indian Philosophy, Volume 1','Dasgupta, Surendranath','',0,539)
 (1022,'Walking','Thoreau, Henry David','',0,539)
 (19163,'Märchen für Kinder','Andersen, H. C. (Hans Christian)','',0,538)
 (41481,'Astounding Stories of Super-Science January 1930','','Meek, S. P. (Sterner St. Paul);Cummings, Ray;Pelcher, Anthony;Staley, M. L.;Bates, Harry;Tench, C. V.;Rousseau, Victor;Leinster, Murray',0,538)
 (55225,'Victor Serenus','Wood, Henry, Mrs.','',0,537)
 (55348,'The Red-headed Man','Hume, Fergus','',0,536)
 (216,'The Tao Teh King, or the Tao and its Characteristics','Laozi','Legge, James',0,536)
 (641,'The Violet Fairy Book','Lang, Andrew','',0,135)
 (9182,'Villette','Brontë, Charlotte','',0,532)
 (6133,'The Extraordinary Adventures of Arsene Lupin, Gentleman-Burglar','Leblanc, Maurice','',0,532)
 (11030,'Incidents in the Life of a Slave Girl, Written by Herself','Jacobs, Harriet A. (Harriet Ann)','Child, Lydia Maria',0,532)
 (5343,'Rainbow Valley','Montgomery, L. M. (Lucy Maud)','',0,528)
 (1164,'The Iron Heel','London, Jack','',0,528)
 (32,'Herland','Gilman, Charlotte Perkins','',0,527)
 (7471,'The Man with Two Left Feet, and Other Stories','Wodehouse, P. G. (Pelham Grenville)','',0,527)
 (2981,'The Memoirs of Jacques Casanova de Seingalt, 1725-1798. Complete','Casanova, Giacomo','Machen, Arthur',0,527)
 (55261,'Nothing of Importance A record of eight months at the front with a Welsh battalion, October, 1915, to June, 1916','Adams, John Bernard Pye','',0,527)
 (41907,'Demian: Die Geschichte von Emil Sinclairs Jugend','Hesse, Hermann','',0,526)
 (1600,'Symposium','Plato','Jowett, Benjamin',0,526)
 (2435,'The Crimson Fairy Book','Lang, Andrew','',0,126)
 (55260,'Humours of &apos;37, Grave, Gay and Grim Rebellion Times in the Canadas','Lizars, Kathleen MacFarlane','Lizars, Robina',0,525)
 (2848,'Antiquities of the Jews','Josephus, Flavius','Whiston, William',0,525)
 (73,'The Red Badge of Courage: An Episode of the American Civil War','Crane, Stephen','',0,525)
 (54893,'The Secrets of the Harem','Anonymous','',0,524)
 (70,'What Is Man? and Other Essays','Twain, Mark','',0,523)
 (15272,'Spenser&apos;s The Faerie Queene, Book I','Spenser, Edmund','Wauchope, George Armstrong',0,523)
 (5683,'The Critique of Practical Reason','Kant, Immanuel','Abbott, Thomas Kingsmill',0,522)
 (369,'The Outlaw of Torn','Burroughs, Edgar Rice','',0,120)
 (38070,'The Norwegian Fairy Book','Stroebe, Klara','Hood, George Washington;Martens, Frederick Herman',0,119)
 (5615,'The Pink Fairy Book','Lang, Andrew','',0,119)
 (55282,'Work','Zola, Émile','Vizetelly, Ernest Alfred',0,519)
 (7277,'The Green Fairy Book','','Lang, Andrew',0,117)
 (55375,'Famous Frosts and Frost Fairs in Great Britain Chronicled from the Earliest to the Present Time','Andrews, William','',0,516)
 (1212,'Love and Freindship [sic]','Austen, Jane','',0,515)
 (331,'The Mucker','Burroughs, Edgar Rice','',0,114)
 (3796,'Rilla of Ingleside','Montgomery, L. M. (Lucy Maud)','',0,513)
 (2267,'Othello','Shakespeare, William','',0,513)
 (16966,'Shakespearean Tragedy: Lectures on Hamlet, Othello, King Lear, Macbeth','Bradley, A. C. (Andrew Cecil)','',0,511)
 (29939,'The Chinese Fairy Book','','Wilhelm, Richard',0,110)
 (10623,'Plays','Glaspell, Susan','',0,510)
 (35898,'The Seven Lamps of Architecture','Ruskin, John','',0,509)
 (27,'Far from the Madding Crowd','Hardy, Thomas','',0,507)
 (1965,'Captain Blood','Sabatini, Rafael','',0,505)
 (27805,'The Wind in the Willows','Grahame, Kenneth','Bransom, Paul',0,505)
 (5921,'The History of Don Quixote, Volume 1, Complete','Cervantes Saavedra, Miguel de','Ormsby, John;Doré, Gustave',0,504)
 (3282,'The Brown Fairy Book','Lang, Andrew','',0,102)
 (10662,'The Night Land','Hodgson, William Hope','',0,501)
 (601,'The Monk: A Romance','Lewis, M. G. (Matthew Gregory)','',0,500)
 (550,'Silas Marner','Eliot, George','',0,500)
 (6593,'History of Tom Jones, a Foundling','Fielding, Henry','',0,500)
 (55231,'A History of the Peninsular War, Vol. III Sep. 1809 - Dec. 1810. Ocaña, Cadiz, Bussaco, Torres Vedras','Oman, Charles','',0,500)
 (19860,'The Arabian Nights Entertainments','Anonymous','Winter, Milo',0,499)
 (55236,'I Canti','Leopardi, Giacomo','',0,498)
 (2038,'The Lock and Key Library: Classic Mystery and Detective Stories: Modern English','','Stevenson, Robert Louis;Hawthorne, Julian;Castle, Egerton;Doyle, Arthur Conan;Weyman, Stanley John;Kipling, Rudyard;Collins, Wilkie',0,498)
 (29728,'Cookery and Dining in Imperial Rome','Apicius','Starr, Frederick;Vehling, Joseph Dommers',0,498)
 (33525,'Stories from Tagore','Tagore, Rabindranath','',0,496)
 (3074,'The Burgess Bird Book for Children','Burgess, Thornton W. (Thornton Waldo)','',0,496)
 (3206,'Moby Multiple Language Lists of Common Words','Ward, Grady','',0,494)
 (364,'The Mad King','Burroughs, Edgar Rice','',0,92)
 (2040,'Confessions of an English Opium-Eater','De Quincey, Thomas','',0,492)
 (700,'The Old Curiosity Shop','Dickens, Charles','',0,490)
 (32202,'The Irish Fairy Book','','Denham, George;Graves, Alfred Perceval',0,89)
 (1091,'On Heroes, Hero-Worship, and the Heroic in History','Carlyle, Thomas','',0,489)
 (3761,'This Country of Ours','Marshall, H. E. (Henrietta Elizabeth)','',0,488)
 (27826,'The Olive Fairy Book','','Ford, H. J. (Henry Justice);Lang, Andrew',0,88)
 (1719,'The Ballad of the White Horse','Chesterton, G. K. (Gilbert Keith)','',0,487)
 (3454,'The Lilac Fairy Book','Lang, Andrew','',0,85)
 (55402,'Our Fellows Skirmishes with the Swamp Dragoons','Castlemon, Harry','',0,482)
 (3420,'A Vindication of the Rights of Woman&#13; With Strictures on Political and Moral Subjects','Wollstonecraft, Mary','',0,482)
 (1170,'Anabasis','Xenophon','Dakyns, Henry Graham',0,480)
 (10136,'The Book of Household Management','Beeton, Mrs. (Isabella Mary)','',0,480)
 (55303,'Winona, A Dakota Legend And Other Poems','Huggins, Eli L.','',0,479)
 (54734,'Tales of Laughter A third fairy book','Smith, Nora Archibald','Wiggin, Kate Douglas Smith',0,79)
 (3435,'The Book of the Thousand Nights and a Night — Volume 01','','Burton, Richard Francis, Sir',0,478)
 (5658,'Lord Jim','Conrad, Joseph','',0,478)
 (12758,'Library of the World&apos;s Best Mystery and Detective Stories','','Apuleius;Mille, Pierre;Capuana, Luigi;Hawthorne, Julian;Erckmann-Chatrian;Pliny, the Younger;Maupassant, Guy de;Balzac, Honoré de;Voltaire;Alarcón, Pedro Antonio de;Villiers de L&apos;Isle-Adam, Auguste, comte de',0,478)
 (55191,'A History of North American Birds, Land Birds - Volume 1','Baird, Spencer Fullerton','Ridgway, Robert;Brewer, Thomas Mayo',0,477)
 (6746,'The Grey Fairy Book','','Lang, Andrew',0,76)
 (32154,'The Variable Man','Dick, Philip K.','Ebel, Alex',0,476)
 (55255,'Anecdotes of Big Cats and Other Beasts','Wilson, David Alec','',0,476)
 (40196,'The Oxford Book of American Essays','','Butler, Nicholas Murray;Winthrop, Theodore;Eliot, Charles William;Lodge, Henry Cabot;Brownell, W. C. (William Crary);Curtis, George William;Irving, Washington;Lowell, James Russell;Martin, Edward Sandford;King, Clarence;Matthews, Brander;Crothers, Samuel McChord;Higginson, Thomas Wentworth;Thoreau, Henry David;Roosevelt, Theodore;James, Henry;Dana, Richard Henry;Trent, William P. (William Peterfield);Burroughs, John;Hawthorne, Nathaniel;Franklin, Benjamin;Emerson, Ralph Waldo;Poe, Edgar Allan;Warner, Charles Dudley;Whitman, Walt;Mabie, Hamilton Wright;Howells, William Dean;Holmes, Oliver Wendell',0,476)
 (143,'The Mayor of Casterbridge','Hardy, Thomas','',0,475)
 (12122,'The Monkey&apos;s Paw The Lady of the Barge and Others, Part 2.','Jacobs, W. W. (William Wymark)','',0,474)
 (19778,'Alice&apos;s Abenteuer im Wunderland','Carroll, Lewis','Tenniel, John;Zimmermann, Antonie',0,473)
 (6098,'Amelia — Complete','Fielding, Henry','',0,473)
 (10681,'Roget&apos;s Thesaurus of English Words and Phrases','Roget, Peter Mark','',0,472)
 (55313,'The Vanishing of Tera','Hume, Fergus','',0,472)
 (55347,'Reminiscences of Prince Talleyrand, Volume I (of 2)','Colmache, Édouard','Colmache, Madame',0,472)
 (25447,'Mysticism and Logic and Other Essays','Russell, Bertrand','',0,472)
 (816,'Democracy in America — Volume 2','Tocqueville, Alexis de','Reeve, Henry',0,472)
 (363,'The Oakdale Affair','Burroughs, Edgar Rice','',0,71)
 (119,'A Tramp Abroad','Twain, Mark','',0,469)
 (20228,'Noli Me Tangere','Rizal, José','Poblete, Pascual Hicaro',0,469)
 (38280,'Modern Essays','','Sherman, Stuart Pratt;Guiney, Louise Imogen;Conrad, Joseph;White, William Allen;Herbert, A. P. (Alan Patrick);Smith, Logan Pearsall;Holliday, Robert Cortes;Belloc, Hilaire;Ayres, Harry Morgan;Marquis, Don;Milne, A. A. (Alan Alexander);Dounce, Harry Esty;Russell, Bertrand;Brooke, Rupert;Firkins, Oscar W.;Storm, Marian;Tomlinson, H. M. (Henry Major);Broun, Heywood;Saintsbury, George;White, Stewart Edward;Bone, David W. (David William);Beerbohm, Max, Sir;Utter, Robert Palfrey;McFee, William;Guedalla, Philip;Osler, William;Kilmer, Joyce;Macy, John Albert;Leacock, Stephen;Burke, Thomas;Strunsky, Simeon;Cabell, James Branch;Santayana, George;Morley, Christopher',0,469)
 (37532,'The Scottish Fairy Book','Grierson, Elizabeth W. (Elizabeth Wilson)','Williams, Morris Meredith',0,68)
 (20916,'The Arabian Nights: Their Best-known Tales','','Parrish, Maxfield;Smith, Nora Archibald;Wiggin, Kate Douglas Smith',0,468)
 (55342,'Pine Tree Ballads Rhymed Stories of Unplaned Human Natur&apos; up in Maine','Day, Holman F.','',0,468)
 (9830,'The Beautiful and Damned','Fitzgerald, F. Scott (Francis Scott)','',0,467)
 (274,'Disputation of Doctor Martin Luther on the Power and Efficacy of Indulgences','Luther, Martin','',0,466)
 (42474,'1000 Mythological Characters Briefly Described Adapted to Private Schools, High Schools and Academies','Ellis, Edward Sylvester','',0,465)
 (7841,'A Primary Reader: Old-time Stories, Fairy Tales and Myths Retold by Children','Smythe, E. Louise (Emma Louise)','',0,465)
 (102,'The Tragedy of Pudd&apos;nhead Wilson','Twain, Mark','',0,464)
 (8486,'Ghost Stories of an Antiquary','James, M. R. (Montague Rhodes)','',0,464)
 (10636,'The Travels of Marco Polo — Volume 1','Rustichello of Pisa','Yule, Henry, Sir;Cordier, Henri;Polo, Marco',0,463)
 (55307,'The Black Monk and other Stories','Tchekhoff, Anton','Long, Robert Edward Crozier',0,463)
 (4763,'The Game of Logic','Carroll, Lewis','',0,462)
 (55186,'Cassell&apos;s History of England, Vol. 4 (of 8)&#13; From the Fall of Marlborough to the Peninsular War','Anonymous','',0,461)
 (55400,'Common Cause A Novel of the War in America','Adams, Samuel Hopkins','Brown, Arthur William',0,460)
 (28314,'The Yellow Fairy Book','','Ford, H. J. (Henry Justice);Lang, Andrew',0,60)
 (3475,'The Efficiency Expert','Burroughs, Edgar Rice','',0,58)
 (25929,'Daemonologie.','James I, King of England','',0,458)
 (1081,'Dead Souls','Gogol, Nikolai Vasilevich','Hogarth, D. J.',0,457)
 (470,'Heretics','Chesterton, G. K. (Gilbert Keith)','',0,456)
 (55308,'Progress and Poverty, Volume  I (of 2) An Inquiry into the Cause of Industrial Depressions and of Increase of Want with Increase of Wealth','George, Henry','',0,456)
 (25609,'A Child&apos;s Garden of Verses','Stevenson, Robert Louis','Smith, Jessie Willcox',0,456)
 (537,'Tales of Terror and Mystery','Doyle, Arthur Conan','',0,456)
 (28696,'Symbolic Logic','Carroll, Lewis','',0,454)
 (8578,'The Grand Inquisitor','Dostoyevsky, Fyodor','Blavatsky, H. P. (Helena Petrovna)',0,454)
 (24811,'Viking Tales','Hall, Jennie','Lambdin, Victor Ralph',0,453)
 (55333,'The History Teacher&apos;s Magazine, Vol. I, No. 4, December, 1909','Various','',0,452)
 (35830,'The 2010 CIA World Factbook','United States. Central Intelligence Agency','',0,451)
 (39509,'The Black Man, the Father of Civilization, Proven by Biblical History','Webb, James Morris','',0,450)
 (7700,'Lysistrata','Aristophanes','Lindsay, Norman;Lindsay, Jack',0,450)
 (55311,'The Girl from Malta','Hume, Fergus','',0,449)
 (20417,'The Outline of Science, Vol. 1 (of 4) A Plain Story Simply Told','Thomson, J. Arthur (John Arthur)','',0,449)
 (26019,'Europa&apos;s Fairy Book','Jacobs, Joseph','Batten, John Dickson',0,49)
 (55340,'Squire Phin','Day, Holman','',0,448)
 (685,'The Atomic Bombings of Hiroshima and Nagasaki','United States. Army. Corps of Engineers. Manhattan District','',0,448)
 (8147,'The Man Who Would Be King','Kipling, Rudyard','',0,447)
 (29635,'Dr. Montessori&apos;s Own Handbook','Montessori, Maria','',0,446)
 (37193,'The Swedish Fairy Book','','Hood, George Washington;Martens, Frederick Herman;Stroebe, Klara',0,44)
 (37995,'The Diamond Fairy Book','Various','Papé, Frank Cheyne;Millar, H. R. (Harold Robert)',0,44)
 (12096,'Bushido, the Soul of Japan','Nitobe, Inazo','',0,444)
 (14091,'Barkham Burroughs&apos; Encyclopaedia of Astounding Facts and Useful Information, 1889','Burroughs, Barkham','',0,43)
 (13529,'The Influence of Sea Power Upon History, 1660-1783','Mahan, A. T. (Alfred Thayer)','',0,442)
 (27638,'The 2001 CIA World Factbook','United States. Central Intelligence Agency','',0,441)
 (18900,'A Text-Book of the History of Painting','Van Dyke, John Charles','',0,440)
 (24737,'The Children of Odin: The Book of Northern Myths','Colum, Padraic','Pogány, Willy',0,439)
 (55376,'The Piccadilly Puzzle A Mysterious Story','Hume, Fergus','',0,438)
 (151,'The Rime of the Ancient Mariner','Coleridge, Samuel Taylor','',0,438)
 (19207,'The Firelight Fairy Book','Beston, Henry','',0,38)
 (9662,'An Enquiry Concerning Human Understanding','Hume, David','Selby-Bigge, L. A. (Lewis Amherst), Sir',0,437)
 (10657,'"De Bello Gallico" and Other Commentaries','Caesar, Julius','McDevitte, W. A. (William Alexander);De Quincey, Thomas',0,436)
 (30249,'Ways of Nature','Burroughs, John','',0,36)
 (3567,'Memoirs of Napoleon Bonaparte — Complete','Bourrienne, Louis Antoine Fauvelet de','Phipps, Ramsay Weston',0,435)
 (2895,'Following the Equator: A Journey Around the World','Twain, Mark','',0,434)
 (36532,'The Orange Fairy Book','','Lang, Andrew;Ford, H. J. (Henry Justice)',0,34)
 (17860,'Stories from Hans Andersen','Andersen, H. C. (Hans Christian)','Dulac, Edmund',0,433)
 (501,'The Story of Doctor Dolittle','Lofting, Hugh','Walpole, Hugh, Sir',0,432)
 (19719,'The Art Of Writing &amp; Speaking The English Language Word-Study and Composition &amp; Rhetoric','Cody, Sherwin','',0,432)
 (37348,'The Old-Fashioned Fairy Book','Harrison, Burton, Mrs.','Sherwood, Rosina Emmet',0,32)
 (33547,'The Grey Fairy Book','','Ford, H. J. (Henry Justice);Lang, Andrew',0,31)
 (31201,'The Brown Fairy Book','Lang, Andrew','Ford, H. J. (Henry Justice)',0,30)
 (128,'The Arabian Nights Entertainments','Lang, Andrew','',0,430)
 (55264,'On Growth and Form','Thompson, D&apos;Arcy Wentworth','',0,429)
 (55292,'The Scaring Off Of Teddy Dawson','Brighouse, Harold','',0,429)
 (36008,'The Blue Rose Fairy Book','Baring, Maurice','',0,29)
 (44127,'Fresh Fields','Burroughs, John','',0,27)
 (3163,'Birds and Bees, Sharp Eyes, and Other Papers','Burroughs, John','',0,27)
 (7986,'Plays by Anton Chekhov, Second Series','Chekhov, Anton Pavlovich','West, Julius',0,426)
 (55332,'The Republic of Ragusa An Episode of the Turkish Conquest','Villary, Luigi','Hulton, William',0,426)
 (22994,'The Frontier in American History','Turner, Frederick Jackson','',0,425)
 (34099,'In Stahlgewittern, aus dem Tagebuch eines Stoßtruppführers','Jünger, Ernst','',0,424)
 (657,'The Anglo-Saxon Chronicle','','Ingram, J. (James);Giles, J. A. (John Allen)',0,424)
 (26386,'Laboulaye&apos;s Fairy Book','Laboulaye, Édouard','Booth, Mary L. (Mary Louise);Wiggin, Kate Douglas Smith;McCandlish, Edward',0,23)
 (55324,'In Spite of All A Novel','Lyall, Edna','',0,422)
 (24388,'Squirrels and Other Fur-Bearers','Burroughs, John','',0,22)
 (17157,'Gulliver&apos;s Travels into Several Remote Regions of the World','Swift, Jonathan','Balliet, Thomas M. (Thomas Minard)',0,422)
 (35688,'Alice in Wonderland&#13; A Dramatization of Lewis Carroll&apos;s "Alice&apos;s Adventures in Wonderland" and "Through the Looking Glass"','Carroll, Lewis','Gerstenberg, Alice',0,421)
 (55272,'Kings-at-Arms','Bowen, Marjorie','',0,421)
 (55328,'The Speculations of John Steele','Barr, Robert','Gruger, Frederic Rodrigo',0,421)
 (35458,'The Green Forest Fairy Book','Brady, Loretta Ellen','Preston, Alice Bolam',0,20)
 (6409,'How to Speak and Write Correctly','Devlin, Joseph','',0,420)
 (30240,'The Big Trip Up Yonder','Vonnegut, Kurt','Kossin, Sandy',0,420)
 (17989,'Le comte de Monte-Cristo, Tome I','Dumas, Alexandre','',0,420)
 (11027,'Grimm&apos;s Fairy Stories','Grimm, Wilhelm','Owen, Robert Emmett;Gruelle, Johnny;Grimm, Jacob',0,419)
 (27321,'Fairy Book','May, Sophie','',0,17)
 (38326,'Bede&apos;s Ecclesiastical History of England','Bede, the Venerable, Saint','Sellar, A. M.',0,416)
 (27083,'The Subjection of Women','Mill, John Stuart','',0,416)
 (55192,'A History of North American Birds, Land Birds - Volume 2','Baird, Spencer Fullerton','Ridgway, Robert;Brewer, Thomas Mayo',0,416)
 (18335,'The Breath of Life','Burroughs, John','',0,15)
 (153,'Jude the Obscure','Hardy, Thomas','',0,415)
 (3268,'The Mysteries of Udolpho','Radcliffe, Ann Ward','',0,414)
 (5177,'Birds and Poets : with Other Papers','Burroughs, John','',0,14)
 (54307,'Tarzanin paluu Seikkailukirja Afrikan aarniometsistä','Burroughs, Edgar Rice','Hedman, Valfrid',0,14)
 (53984,'Tarzan, apinain kuningas Seikkailuromaani Afrikan aarniometsistä','Burroughs, Edgar Rice','',0,13)
 (55278,'Chess Generalship, Vol. I. Grand Reconnaissance','Young, Franklin K.','',0,413)
 (36805,'Spanish Tales for Beginners','','Hills, E. C. (Elijah Clarence);Reinhardt, Louise',0,413)
 (33053,'Camping &amp; Tramping with Roosevelt','Burroughs, John','',0,13)
 (6695,'Tales of the Jazz Age','Fitzgerald, F. Scott (Francis Scott)','',0,412)
 (7404,'John James Audubon','Burroughs, John','',0,11)
 (30342,'Whitman: A Study','Burroughs, John','',0,11)
 (23042,'The Tempest The Works of William Shakespeare [Cambridge Edition] [9 vols.]','Shakespeare, William','Glover, John, librarian of Trinity College, Cambridge;Clark, William George',0,410)
 (8121,'Ghosts','Ibsen, Henrik','Archer, William',0,410)
 (55329,'Young Lord Stranleigh A Novel','Barr, Robert','Anonymous',0,410)
 (11224,'Utilitarianism','Mill, John Stuart','',0,410)
;

